Crashloopbackoff condition
Signed-off-by: PrimalPimmy <Prashant20.pm@gmail.com>

diff --git a/.github/workflows/ci-test-controllers.yml b/.github/workflows/ci-test-controllers.yml
--- a/.github/workflows/ci-test-controllers.yml
+++ b/.github/workflows/ci-test-controllers.yml
@@ -80,10 +80,15 @@ jobs:
             kubectl apply -f -
           fi
           kubectl wait -n kubearmor --timeout=5m --for=jsonpath='{.status.phase}'=Running kubearmorconfigs/kubearmorconfig-test
-          while true; do
-            kubectl get pod -n kubearmor -l kubearmor-app,kubearmor-app!=kubearmor-snitch | grep Running > /dev/null && break || echo "Waiting for kubearmor pods"
-            sleep 1
-          done
+          timeout 7m bash -c -- 'while true; do
+           kubectl get pod -n kubearmor -l kubearmor-app,kubearmor-app!=kubearmor-snitch | grep Running > /dev/null && break || echo "Waiting for kubearmor pods"
+           sleep 1
+           if 
+           kubectl get pod -n kubearmor -l kubearmor-app,kubearmor-app!=kubearmor-snitch | grep CrashLoopBackOff; then
+           echo "Error: Pod in CrashLoopBackOff state"
+           exit 1
+           fi
+          done'
           kubectl get pods -A
 
       - name: Test KubeArmor using Ginkgo
